### ISSUE TITLE
Title: Behavior of Mobile Navigation Menu

### ISSUE THREAD

**Issue by SHAKUURR** [ernestechie/receiptsync#16]
### **Title: Behavior of Mobile Navigation Menu**

**
https://user-images.githubusercontent.com/108751084/225241812-86183771-40c7-4d02-a737-813889e08c90.mp4
** 

             I came across your project few days ago on Twitter, and I must say, It's super amazing. Building a dashboard and adding those features alongside really shows that you are a boss and I really love your consistency. I can't wait to be like you when I grow up😊. 
            
            However, I will like to call your attention to the behavior of the navigation bar on mobile, where  clicking on a menu item in the navigation bar does not close the menu on mobile devices. Additionally, clicking outside the navigation bar does not close the menu, which causes inconsistency in the user experience. As a user of this lovely project, I believe that this issue could potentially affect the user experience negatively. Therefore, I suggest investigating the issue and fixing it to ensure consistent and smooth user interaction with the navigation menu. 

Thank you for your attention to this matter, I also attached a short DEMO on it. 

Best regards, 
SHAKUR

**Comment by ernestechie** [comment]
Thank you for that observation. I’ll fix it as soon as possible.

**Comment by ernestechie** [comment]
FIXED: Clicking on a menu item in the navigation bar will now close the menu on mobile devices.

**Comment by SHAKUURR** [comment]
Amazing job, boss. ❤❤❤❤
